[package]
name = "werewolf_services"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10.0"
actix-web = "3"
actix-web-actors = "3"
serde = "1"
dotenv = "0.15.0"
env_logger = "0.9.0"
