version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: actix
      POSTGRES_USER: actix
      POSTGRES_PASSWORD: actix
  web:
    build: ./
    restart: always
    ports:
      - "3000:8080"
    depends_on:
      - db
    links:
      - db
