version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: actix
      POSTGRES_USER: actix
      POSTGRES_PASSWORD: actix
